server:
  port: 8081

spring:
  application:
    name: STAFF-SERVICE

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/staff_management_module
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root




  servlet:
    multipart:
      enabled: 'true '
      file-size-threshold: 1KB
      max-file-size: 300MB

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: ERROR
#    com.auth0.application: TRACE




