version: '3'

services:
  staff-service:
    image: staff-service
    ports:
      - "8081:8081" # Map port 8081 on host to port 8080 in the container
    depends_on:
      - mysqldb
    networks:
      - backend
    volumes:
      - /data/springboot-app


  mysqldb:
    image: mysql:latest
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: staff_management_module

    volumes:
      - /data/mysql

networks:
  backend:
