version: '3'

services:
  mmc-staff-service:
    build: ./mmc-staff-management-service
    ports:
      - "8081:8080" # Map port 8081 on host to port 8080 in the container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
     # - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka/
      - CONFIG_SERVER_URI=http://config-server:8888
    depends_on:
      - service-registry
      - config-server
    networks:
      - backend

  api-gateway:
    build: ./mmc-serivce-api-gateway
    ports:
      - "8080:8080" # Map port 8080 on host to port 8080 in the container
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #  - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - service-registry
    networks:
      - backend

  service-registry:
    build: ./mmc-service-registry
    ports:
      - "8761:8761" # Map port 8761 on host to port 8761 in the container
    networks:
      - backend

  config-server:
    build: ./mmc-service-config-server
    ports:
      - "8888:8888" # Map port 8888 on host to port 8888 in the container
    networks:
      - backend

networks:
  backend:
