server:
  port: 8080

spring:
  application:
    name: MMC-SERVICE-API-GATEWAY
  config:
    import: optional:configserver:http://13.201.121.103:8888
   # import: optional:configserver:http://localhost:8085


  cloud:
    gateway:
      routes:
        - id: MMC-STAFF-MANAGEMENT-SERVICE
          uri: lb://MMC-STAFF-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/**


